{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Room_Size</th>\n",
       "      <th>Container_Volume_(cc)</th>\n",
       "      <th>Room_Pressure_(psi)</th>\n",
       "      <th>Room _Temp (C)</th>\n",
       "      <th>Pressure_loss_(psi)</th>\n",
       "      <th>Age of Pipe</th>\n",
       "      <th>CO Sensor value in MQ-9</th>\n",
       "      <th>Time_(sec)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>300</td>\n",
       "      <td>44500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.0100</td>\n",
       "      <td>20</td>\n",
       "      <td>348</td>\n",
       "      <td>54</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>100</td>\n",
       "      <td>25400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>34</td>\n",
       "      <td>0.0860</td>\n",
       "      <td>19</td>\n",
       "      <td>516</td>\n",
       "      <td>180</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>500</td>\n",
       "      <td>22250</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.0200</td>\n",
       "      <td>35</td>\n",
       "      <td>485</td>\n",
       "      <td>45</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>150</td>\n",
       "      <td>19850</td>\n",
       "      <td>14.7</td>\n",
       "      <td>25</td>\n",
       "      <td>0.0185</td>\n",
       "      <td>41</td>\n",
       "      <td>415</td>\n",
       "      <td>78</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>285</td>\n",
       "      <td>11000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.1120</td>\n",
       "      <td>7</td>\n",
       "      <td>625</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Room_Size  Container_Volume_(cc)  Room_Pressure_(psi)  Room _Temp (C)  \\\n",
       "0        300                  44500                 14.7              32   \n",
       "1        100                  25400                 14.7              34   \n",
       "2        500                  22250                 14.7              30   \n",
       "3        150                  19850                 14.7              25   \n",
       "4        285                  11000                 14.7              32   \n",
       "\n",
       "   Pressure_loss_(psi)  Age of Pipe  CO Sensor value in MQ-9  Time_(sec)  \n",
       "0               0.0100           20                      348          54  \n",
       "1               0.0860           19                      516         180  \n",
       "2               0.0200           35                      485          45  \n",
       "3               0.0185           41                      415          78  \n",
       "4               0.1120            7                      625          26  "
      ]
     },
     "execution_count": 57,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv('Gas Leakage Dataset Final - Sheet1.csv')\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Room_Size</th>\n",
       "      <th>Container_Volume_(cc)</th>\n",
       "      <th>Room_Pressure_(psi)</th>\n",
       "      <th>Room _Temp (C)</th>\n",
       "      <th>Pressure_loss_(psi)</th>\n",
       "      <th>Age of Pipe</th>\n",
       "      <th>CO Sensor value in MQ-9</th>\n",
       "      <th>Time_(sec)</th>\n",
       "      <th>Leak_Rate_(scc/m)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>300</td>\n",
       "      <td>44500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.0100</td>\n",
       "      <td>20</td>\n",
       "      <td>348</td>\n",
       "      <td>54</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>100</td>\n",
       "      <td>25400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>34</td>\n",
       "      <td>0.0860</td>\n",
       "      <td>19</td>\n",
       "      <td>516</td>\n",
       "      <td>180</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>500</td>\n",
       "      <td>22250</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.0200</td>\n",
       "      <td>35</td>\n",
       "      <td>485</td>\n",
       "      <td>45</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>150</td>\n",
       "      <td>19850</td>\n",
       "      <td>14.7</td>\n",
       "      <td>25</td>\n",
       "      <td>0.0185</td>\n",
       "      <td>41</td>\n",
       "      <td>415</td>\n",
       "      <td>78</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>285</td>\n",
       "      <td>11000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.1120</td>\n",
       "      <td>7</td>\n",
       "      <td>625</td>\n",
       "      <td>26</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Room_Size  Container_Volume_(cc)  Room_Pressure_(psi)  Room _Temp (C)  \\\n",
       "0        300                  44500                 14.7              32   \n",
       "1        100                  25400                 14.7              34   \n",
       "2        500                  22250                 14.7              30   \n",
       "3        150                  19850                 14.7              25   \n",
       "4        285                  11000                 14.7              32   \n",
       "\n",
       "   Pressure_loss_(psi)  Age of Pipe  CO Sensor value in MQ-9  Time_(sec)  \\\n",
       "0               0.0100           20                      348          54   \n",
       "1               0.0860           19                      516         180   \n",
       "2               0.0200           35                      485          45   \n",
       "3               0.0185           41                      415          78   \n",
       "4               0.1120            7                      625          26   \n",
       "\n",
       "  Leak_Rate_(scc/m)  \n",
       "0                    \n",
       "1                    \n",
       "2                    \n",
       "3                    \n",
       "4                    "
      ]
     },
     "execution_count": 58,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.insert(8,\"Leak_Rate_(scc/m)\",\"\")\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.DataFrame()\n",
    "data['numerator'] = df['Container_Volume_(cc)']*df['Pressure_loss_(psi)']\n",
    "data['denominator'] = df['Time_(sec)']*df['Room_Pressure_(psi)']\n",
    "df.loc[df['CO Sensor value in MQ-9'] >=212, 'Leak_Rate_(scc/m)'] = (data['numerator']/data['denominator'])*60\n",
    "df.loc[df['CO Sensor value in MQ-9'] <212, 'Leak_Rate_(scc/m)'] = 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Room_Size</th>\n",
       "      <th>Container_Volume_(cc)</th>\n",
       "      <th>Room_Pressure_(psi)</th>\n",
       "      <th>Room _Temp (C)</th>\n",
       "      <th>Pressure_loss_(psi)</th>\n",
       "      <th>Age of Pipe</th>\n",
       "      <th>CO Sensor value in MQ-9</th>\n",
       "      <th>Time_(sec)</th>\n",
       "      <th>Leak_Rate_(scc/m)</th>\n",
       "      <th>Intensity</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>300</td>\n",
       "      <td>44500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.0100</td>\n",
       "      <td>20</td>\n",
       "      <td>348</td>\n",
       "      <td>54</td>\n",
       "      <td>33.635676</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>100</td>\n",
       "      <td>25400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>34</td>\n",
       "      <td>0.0860</td>\n",
       "      <td>19</td>\n",
       "      <td>516</td>\n",
       "      <td>180</td>\n",
       "      <td>49.532880</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>500</td>\n",
       "      <td>22250</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.0200</td>\n",
       "      <td>35</td>\n",
       "      <td>485</td>\n",
       "      <td>45</td>\n",
       "      <td>40.362812</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>150</td>\n",
       "      <td>19850</td>\n",
       "      <td>14.7</td>\n",
       "      <td>25</td>\n",
       "      <td>0.0185</td>\n",
       "      <td>41</td>\n",
       "      <td>415</td>\n",
       "      <td>78</td>\n",
       "      <td>19.216379</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>285</td>\n",
       "      <td>11000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.1120</td>\n",
       "      <td>7</td>\n",
       "      <td>625</td>\n",
       "      <td>26</td>\n",
       "      <td>193.406593</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>350</td>\n",
       "      <td>41000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>26</td>\n",
       "      <td>0.0150</td>\n",
       "      <td>15</td>\n",
       "      <td>200</td>\n",
       "      <td>150</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>250</td>\n",
       "      <td>40840</td>\n",
       "      <td>14.7</td>\n",
       "      <td>33</td>\n",
       "      <td>0.0380</td>\n",
       "      <td>19</td>\n",
       "      <td>264</td>\n",
       "      <td>221</td>\n",
       "      <td>28.662296</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>400</td>\n",
       "      <td>50004</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.0250</td>\n",
       "      <td>28</td>\n",
       "      <td>198</td>\n",
       "      <td>287</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>625</td>\n",
       "      <td>75400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>20</td>\n",
       "      <td>0.0540</td>\n",
       "      <td>45</td>\n",
       "      <td>568</td>\n",
       "      <td>38</td>\n",
       "      <td>437.336198</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>280</td>\n",
       "      <td>5241</td>\n",
       "      <td>14.7</td>\n",
       "      <td>29</td>\n",
       "      <td>0.2100</td>\n",
       "      <td>26</td>\n",
       "      <td>521</td>\n",
       "      <td>541</td>\n",
       "      <td>8.303670</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>325</td>\n",
       "      <td>15472</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.1800</td>\n",
       "      <td>4</td>\n",
       "      <td>485</td>\n",
       "      <td>484</td>\n",
       "      <td>23.485917</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>125</td>\n",
       "      <td>8576</td>\n",
       "      <td>14.7</td>\n",
       "      <td>37</td>\n",
       "      <td>0.0190</td>\n",
       "      <td>12</td>\n",
       "      <td>225</td>\n",
       "      <td>111</td>\n",
       "      <td>5.991690</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>345</td>\n",
       "      <td>12365</td>\n",
       "      <td>14.7</td>\n",
       "      <td>28</td>\n",
       "      <td>0.1230</td>\n",
       "      <td>24</td>\n",
       "      <td>700</td>\n",
       "      <td>29</td>\n",
       "      <td>214.059817</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>415</td>\n",
       "      <td>31400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>27</td>\n",
       "      <td>0.0130</td>\n",
       "      <td>34</td>\n",
       "      <td>324</td>\n",
       "      <td>232</td>\n",
       "      <td>7.181562</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>210</td>\n",
       "      <td>31200</td>\n",
       "      <td>14.7</td>\n",
       "      <td>29</td>\n",
       "      <td>0.1340</td>\n",
       "      <td>3</td>\n",
       "      <td>600</td>\n",
       "      <td>30</td>\n",
       "      <td>568.816327</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>240</td>\n",
       "      <td>15200</td>\n",
       "      <td>14.7</td>\n",
       "      <td>25</td>\n",
       "      <td>0.0250</td>\n",
       "      <td>21</td>\n",
       "      <td>249</td>\n",
       "      <td>325</td>\n",
       "      <td>4.772370</td>\n",
       "      <td>ATTENTION REQUIRED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>300</td>\n",
       "      <td>14000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>26</td>\n",
       "      <td>0.0350</td>\n",
       "      <td>24</td>\n",
       "      <td>340</td>\n",
       "      <td>121</td>\n",
       "      <td>16.528926</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>425</td>\n",
       "      <td>30400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>29</td>\n",
       "      <td>0.2900</td>\n",
       "      <td>11</td>\n",
       "      <td>690</td>\n",
       "      <td>25</td>\n",
       "      <td>1439.346939</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>300</td>\n",
       "      <td>21500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.0120</td>\n",
       "      <td>31</td>\n",
       "      <td>325</td>\n",
       "      <td>212</td>\n",
       "      <td>4.967270</td>\n",
       "      <td>ATTENTION REQUIRED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>450</td>\n",
       "      <td>40500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.0150</td>\n",
       "      <td>15</td>\n",
       "      <td>150</td>\n",
       "      <td>145</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>230</td>\n",
       "      <td>44400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>28</td>\n",
       "      <td>0.0240</td>\n",
       "      <td>16</td>\n",
       "      <td>230</td>\n",
       "      <td>200</td>\n",
       "      <td>21.746939</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>450</td>\n",
       "      <td>50000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>31</td>\n",
       "      <td>0.0210</td>\n",
       "      <td>26</td>\n",
       "      <td>223</td>\n",
       "      <td>130</td>\n",
       "      <td>32.967033</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>320</td>\n",
       "      <td>45500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>26</td>\n",
       "      <td>0.3500</td>\n",
       "      <td>42</td>\n",
       "      <td>546</td>\n",
       "      <td>300</td>\n",
       "      <td>216.666667</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>333</td>\n",
       "      <td>34570</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.0130</td>\n",
       "      <td>10</td>\n",
       "      <td>195</td>\n",
       "      <td>149</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>230</td>\n",
       "      <td>35000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>25</td>\n",
       "      <td>0.2340</td>\n",
       "      <td>5</td>\n",
       "      <td>690</td>\n",
       "      <td>530</td>\n",
       "      <td>63.072776</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>120</td>\n",
       "      <td>10100</td>\n",
       "      <td>14.7</td>\n",
       "      <td>28</td>\n",
       "      <td>0.0140</td>\n",
       "      <td>8</td>\n",
       "      <td>202</td>\n",
       "      <td>195</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>400</td>\n",
       "      <td>14000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>35</td>\n",
       "      <td>0.2500</td>\n",
       "      <td>15</td>\n",
       "      <td>678</td>\n",
       "      <td>20</td>\n",
       "      <td>714.285714</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>550</td>\n",
       "      <td>23000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>34</td>\n",
       "      <td>0.0230</td>\n",
       "      <td>2</td>\n",
       "      <td>180</td>\n",
       "      <td>150</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>150</td>\n",
       "      <td>30050</td>\n",
       "      <td>14.7</td>\n",
       "      <td>28</td>\n",
       "      <td>0.0290</td>\n",
       "      <td>18</td>\n",
       "      <td>298</td>\n",
       "      <td>90</td>\n",
       "      <td>39.521542</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>430</td>\n",
       "      <td>25000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>29</td>\n",
       "      <td>0.3450</td>\n",
       "      <td>19</td>\n",
       "      <td>700</td>\n",
       "      <td>45</td>\n",
       "      <td>782.312925</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>500</td>\n",
       "      <td>13050</td>\n",
       "      <td>14.7</td>\n",
       "      <td>24</td>\n",
       "      <td>0.0110</td>\n",
       "      <td>31</td>\n",
       "      <td>150</td>\n",
       "      <td>120</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>350</td>\n",
       "      <td>5000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>25</td>\n",
       "      <td>0.1430</td>\n",
       "      <td>13</td>\n",
       "      <td>695</td>\n",
       "      <td>27</td>\n",
       "      <td>108.087680</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>220</td>\n",
       "      <td>8800</td>\n",
       "      <td>14.7</td>\n",
       "      <td>29</td>\n",
       "      <td>0.0220</td>\n",
       "      <td>4</td>\n",
       "      <td>170</td>\n",
       "      <td>152</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>450</td>\n",
       "      <td>10500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>31</td>\n",
       "      <td>0.0390</td>\n",
       "      <td>8</td>\n",
       "      <td>290</td>\n",
       "      <td>225</td>\n",
       "      <td>7.428571</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>500</td>\n",
       "      <td>5000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>24</td>\n",
       "      <td>0.1210</td>\n",
       "      <td>20</td>\n",
       "      <td>590</td>\n",
       "      <td>30</td>\n",
       "      <td>82.312925</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>150</td>\n",
       "      <td>12500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>27</td>\n",
       "      <td>0.0230</td>\n",
       "      <td>30</td>\n",
       "      <td>260</td>\n",
       "      <td>300</td>\n",
       "      <td>3.911565</td>\n",
       "      <td>ATTENTION REQUIRED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>230</td>\n",
       "      <td>10500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>29</td>\n",
       "      <td>0.1340</td>\n",
       "      <td>29</td>\n",
       "      <td>500</td>\n",
       "      <td>340</td>\n",
       "      <td>16.890756</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>350</td>\n",
       "      <td>14000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>34</td>\n",
       "      <td>0.0340</td>\n",
       "      <td>15</td>\n",
       "      <td>423</td>\n",
       "      <td>233</td>\n",
       "      <td>8.338443</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>230</td>\n",
       "      <td>10500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>33</td>\n",
       "      <td>0.0150</td>\n",
       "      <td>30</td>\n",
       "      <td>220</td>\n",
       "      <td>153</td>\n",
       "      <td>4.201681</td>\n",
       "      <td>ATTENTION REQUIRED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>140</td>\n",
       "      <td>9000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>35</td>\n",
       "      <td>0.2320</td>\n",
       "      <td>22</td>\n",
       "      <td>710</td>\n",
       "      <td>25</td>\n",
       "      <td>340.897959</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>450</td>\n",
       "      <td>11500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.0110</td>\n",
       "      <td>34</td>\n",
       "      <td>196</td>\n",
       "      <td>200</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>500</td>\n",
       "      <td>5500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>26</td>\n",
       "      <td>0.2300</td>\n",
       "      <td>20</td>\n",
       "      <td>710</td>\n",
       "      <td>27</td>\n",
       "      <td>191.232048</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>350</td>\n",
       "      <td>10500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>28</td>\n",
       "      <td>0.0340</td>\n",
       "      <td>16</td>\n",
       "      <td>220</td>\n",
       "      <td>150</td>\n",
       "      <td>9.714286</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>225</td>\n",
       "      <td>7000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>29</td>\n",
       "      <td>0.0140</td>\n",
       "      <td>18</td>\n",
       "      <td>330</td>\n",
       "      <td>200</td>\n",
       "      <td>2.000000</td>\n",
       "      <td>ATTENTION REQUIRED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>200</td>\n",
       "      <td>10400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.0230</td>\n",
       "      <td>5</td>\n",
       "      <td>230</td>\n",
       "      <td>120</td>\n",
       "      <td>8.136054</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>150</td>\n",
       "      <td>13400</td>\n",
       "      <td>14.7</td>\n",
       "      <td>32</td>\n",
       "      <td>0.0135</td>\n",
       "      <td>23</td>\n",
       "      <td>195</td>\n",
       "      <td>200</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>600</td>\n",
       "      <td>8000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>35</td>\n",
       "      <td>0.0450</td>\n",
       "      <td>35</td>\n",
       "      <td>350</td>\n",
       "      <td>125</td>\n",
       "      <td>11.755102</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>450</td>\n",
       "      <td>11500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>30</td>\n",
       "      <td>0.1340</td>\n",
       "      <td>29</td>\n",
       "      <td>650</td>\n",
       "      <td>27</td>\n",
       "      <td>232.955404</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>500</td>\n",
       "      <td>9000</td>\n",
       "      <td>14.7</td>\n",
       "      <td>25</td>\n",
       "      <td>0.0250</td>\n",
       "      <td>6</td>\n",
       "      <td>350</td>\n",
       "      <td>120</td>\n",
       "      <td>7.653061</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>230</td>\n",
       "      <td>50500</td>\n",
       "      <td>14.7</td>\n",
       "      <td>28</td>\n",
       "      <td>0.0112</td>\n",
       "      <td>9</td>\n",
       "      <td>190</td>\n",
       "      <td>150</td>\n",
       "      <td>0</td>\n",
       "      <td>SAFE</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Room_Size  Container_Volume_(cc)  Room_Pressure_(psi)  Room _Temp (C)  \\\n",
       "0         300                  44500                 14.7              32   \n",
       "1         100                  25400                 14.7              34   \n",
       "2         500                  22250                 14.7              30   \n",
       "3         150                  19850                 14.7              25   \n",
       "4         285                  11000                 14.7              32   \n",
       "5         350                  41000                 14.7              26   \n",
       "6         250                  40840                 14.7              33   \n",
       "7         400                  50004                 14.7              32   \n",
       "8         625                  75400                 14.7              20   \n",
       "9         280                   5241                 14.7              29   \n",
       "10        325                  15472                 14.7              32   \n",
       "11        125                   8576                 14.7              37   \n",
       "12        345                  12365                 14.7              28   \n",
       "13        415                  31400                 14.7              27   \n",
       "14        210                  31200                 14.7              29   \n",
       "15        240                  15200                 14.7              25   \n",
       "16        300                  14000                 14.7              26   \n",
       "17        425                  30400                 14.7              29   \n",
       "18        300                  21500                 14.7              32   \n",
       "19        450                  40500                 14.7              30   \n",
       "20        230                  44400                 14.7              28   \n",
       "21        450                  50000                 14.7              31   \n",
       "22        320                  45500                 14.7              26   \n",
       "23        333                  34570                 14.7              30   \n",
       "24        230                  35000                 14.7              25   \n",
       "25        120                  10100                 14.7              28   \n",
       "26        400                  14000                 14.7              35   \n",
       "27        550                  23000                 14.7              34   \n",
       "28        150                  30050                 14.7              28   \n",
       "29        430                  25000                 14.7              29   \n",
       "30        500                  13050                 14.7              24   \n",
       "31        350                   5000                 14.7              25   \n",
       "32        220                   8800                 14.7              29   \n",
       "33        450                  10500                 14.7              31   \n",
       "34        500                   5000                 14.7              24   \n",
       "35        150                  12500                 14.7              27   \n",
       "36        230                  10500                 14.7              29   \n",
       "37        350                  14000                 14.7              34   \n",
       "38        230                  10500                 14.7              33   \n",
       "39        140                   9000                 14.7              35   \n",
       "40        450                  11500                 14.7              30   \n",
       "41        500                   5500                 14.7              26   \n",
       "42        350                  10500                 14.7              28   \n",
       "43        225                   7000                 14.7              29   \n",
       "44        200                  10400                 14.7              30   \n",
       "45        150                  13400                 14.7              32   \n",
       "46        600                   8000                 14.7              35   \n",
       "47        450                  11500                 14.7              30   \n",
       "48        500                   9000                 14.7              25   \n",
       "49        230                  50500                 14.7              28   \n",
       "\n",
       "    Pressure_loss_(psi)  Age of Pipe  CO Sensor value in MQ-9  Time_(sec)  \\\n",
       "0                0.0100           20                      348          54   \n",
       "1                0.0860           19                      516         180   \n",
       "2                0.0200           35                      485          45   \n",
       "3                0.0185           41                      415          78   \n",
       "4                0.1120            7                      625          26   \n",
       "5                0.0150           15                      200         150   \n",
       "6                0.0380           19                      264         221   \n",
       "7                0.0250           28                      198         287   \n",
       "8                0.0540           45                      568          38   \n",
       "9                0.2100           26                      521         541   \n",
       "10               0.1800            4                      485         484   \n",
       "11               0.0190           12                      225         111   \n",
       "12               0.1230           24                      700          29   \n",
       "13               0.0130           34                      324         232   \n",
       "14               0.1340            3                      600          30   \n",
       "15               0.0250           21                      249         325   \n",
       "16               0.0350           24                      340         121   \n",
       "17               0.2900           11                      690          25   \n",
       "18               0.0120           31                      325         212   \n",
       "19               0.0150           15                      150         145   \n",
       "20               0.0240           16                      230         200   \n",
       "21               0.0210           26                      223         130   \n",
       "22               0.3500           42                      546         300   \n",
       "23               0.0130           10                      195         149   \n",
       "24               0.2340            5                      690         530   \n",
       "25               0.0140            8                      202         195   \n",
       "26               0.2500           15                      678          20   \n",
       "27               0.0230            2                      180         150   \n",
       "28               0.0290           18                      298          90   \n",
       "29               0.3450           19                      700          45   \n",
       "30               0.0110           31                      150         120   \n",
       "31               0.1430           13                      695          27   \n",
       "32               0.0220            4                      170         152   \n",
       "33               0.0390            8                      290         225   \n",
       "34               0.1210           20                      590          30   \n",
       "35               0.0230           30                      260         300   \n",
       "36               0.1340           29                      500         340   \n",
       "37               0.0340           15                      423         233   \n",
       "38               0.0150           30                      220         153   \n",
       "39               0.2320           22                      710          25   \n",
       "40               0.0110           34                      196         200   \n",
       "41               0.2300           20                      710          27   \n",
       "42               0.0340           16                      220         150   \n",
       "43               0.0140           18                      330         200   \n",
       "44               0.0230            5                      230         120   \n",
       "45               0.0135           23                      195         200   \n",
       "46               0.0450           35                      350         125   \n",
       "47               0.1340           29                      650          27   \n",
       "48               0.0250            6                      350         120   \n",
       "49               0.0112            9                      190         150   \n",
       "\n",
       "   Leak_Rate_(scc/m)           Intensity  \n",
       "0          33.635676    HIGHLY DANGEROUS  \n",
       "1          49.532880    HIGHLY DANGEROUS  \n",
       "2          40.362812    HIGHLY DANGEROUS  \n",
       "3          19.216379           DANGEROUS  \n",
       "4         193.406593    HIGHLY DANGEROUS  \n",
       "5                  0                SAFE  \n",
       "6          28.662296           DANGEROUS  \n",
       "7                  0                SAFE  \n",
       "8         437.336198    HIGHLY DANGEROUS  \n",
       "9           8.303670           DANGEROUS  \n",
       "10         23.485917           DANGEROUS  \n",
       "11          5.991690           DANGEROUS  \n",
       "12        214.059817    HIGHLY DANGEROUS  \n",
       "13          7.181562           DANGEROUS  \n",
       "14        568.816327    HIGHLY DANGEROUS  \n",
       "15          4.772370  ATTENTION REQUIRED  \n",
       "16         16.528926           DANGEROUS  \n",
       "17       1439.346939    HIGHLY DANGEROUS  \n",
       "18          4.967270  ATTENTION REQUIRED  \n",
       "19                 0                SAFE  \n",
       "20         21.746939           DANGEROUS  \n",
       "21         32.967033    HIGHLY DANGEROUS  \n",
       "22        216.666667    HIGHLY DANGEROUS  \n",
       "23                 0                SAFE  \n",
       "24         63.072776    HIGHLY DANGEROUS  \n",
       "25                 0                SAFE  \n",
       "26        714.285714    HIGHLY DANGEROUS  \n",
       "27                 0                SAFE  \n",
       "28         39.521542    HIGHLY DANGEROUS  \n",
       "29        782.312925    HIGHLY DANGEROUS  \n",
       "30                 0                SAFE  \n",
       "31        108.087680    HIGHLY DANGEROUS  \n",
       "32                 0                SAFE  \n",
       "33          7.428571           DANGEROUS  \n",
       "34         82.312925    HIGHLY DANGEROUS  \n",
       "35          3.911565  ATTENTION REQUIRED  \n",
       "36         16.890756           DANGEROUS  \n",
       "37          8.338443           DANGEROUS  \n",
       "38          4.201681  ATTENTION REQUIRED  \n",
       "39        340.897959    HIGHLY DANGEROUS  \n",
       "40                 0                SAFE  \n",
       "41        191.232048    HIGHLY DANGEROUS  \n",
       "42          9.714286           DANGEROUS  \n",
       "43          2.000000  ATTENTION REQUIRED  \n",
       "44          8.136054           DANGEROUS  \n",
       "45                 0                SAFE  \n",
       "46         11.755102           DANGEROUS  \n",
       "47        232.955404    HIGHLY DANGEROUS  \n",
       "48          7.653061           DANGEROUS  \n",
       "49                 0                SAFE  "
      ]
     },
     "execution_count": 61,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "result = [] \n",
    "for value in df[\"Leak_Rate_(scc/m)\"]: \n",
    "    if value >= 30: \n",
    "        result.append(\"HIGHLY DANGEROUS\") \n",
    "    elif value >= 5 and value <30: \n",
    "        result.append(\"DANGEROUS\") \n",
    "    elif value >0 and value<5:\n",
    "        result.append(\"ATTENTION REQUIRED\") \n",
    "    else:\n",
    "        result.append(\"SAFE\")\n",
    "       \n",
    "df[\"Intensity\"] = result    \n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "x= df.iloc[:,1:8].values\n",
    "y = df.iloc[:,9].values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size = 4, train_size = 0.85, random_state = 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(array(['ATTENTION REQUIRED', 'DANGEROUS', 'HIGHLY DANGEROUS', 'SAFE'],\n",
       "       dtype=object),\n",
       " array([ 5, 15, 19, 11], dtype=int64))"
      ]
     },
     "execution_count": 91,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.unique(y,return_counts = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(array(['ATTENTION REQUIRED', 'DANGEROUS', 'HIGHLY DANGEROUS', 'SAFE'],\n",
       "       dtype=object),\n",
       " array([ 5, 11, 15, 11], dtype=int64))"
      ]
     },
     "execution_count": 92,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.unique(ytrain, return_counts=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "KNeighborsClassifier(n_neighbors=3)\n"
     ]
    }
   ],
   "source": [
    "##Build the model\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "model = KNeighborsClassifier(n_neighbors = 3)\n",
    "print(model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "KNeighborsClassifier(n_neighbors=3)"
      ]
     },
     "execution_count": 94,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "##Train the model\n",
    "model.fit(xtrain,ytrain)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['HIGHLY DANGEROUS', 'DANGEROUS', 'DANGEROUS', 'HIGHLY DANGEROUS'],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 95,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ypred = model.predict(xtest)\n",
    "ypred"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['HIGHLY DANGEROUS', 'DANGEROUS', 'DANGEROUS', 'HIGHLY DANGEROUS'],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 96,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ytest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Actual Data</th>\n",
       "      <th>Predicted Data</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>DANGEROUS</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>DANGEROUS</td>\n",
       "      <td>DANGEROUS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "      <td>HIGHLY DANGEROUS</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        Actual Data    Predicted Data\n",
       "0  HIGHLY DANGEROUS  HIGHLY DANGEROUS\n",
       "1         DANGEROUS         DANGEROUS\n",
       "2         DANGEROUS         DANGEROUS\n",
       "3  HIGHLY DANGEROUS  HIGHLY DANGEROUS"
      ]
     },
     "execution_count": 97,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.DataFrame()\n",
    "df[\"Actual Data\"] = ytest\n",
    "df[\"Predicted Data\"] = ypred\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[2, 0],\n",
       "       [0, 2]], dtype=int64)"
      ]
     },
     "execution_count": 98,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.metrics import confusion_matrix\n",
    "cm = confusion_matrix(ytest,ypred)\n",
    "cm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import accuracy_score\n",
    "accu = accuracy_score(ytest,ypred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1.0"
      ]
     },
     "execution_count": 100,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "accu"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [],
   "source": [
    "accuracy = []\n",
    "k_value = []\n",
    "for k in range(35):\n",
    "  if k != 0:\n",
    "    model = KNeighborsClassifier(n_neighbors=k)\n",
    "    model.fit(xtrain,ytrain)\n",
    "    ypred = model.predict(xtest)\n",
    "    accu = accuracy_score(ytest,ypred)\n",
    "    accuracy.append(accu)\n",
    "    k_value.append(k)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXQAAAD4CAYAAAD8Zh1EAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/Il7ecAAAACXBIWXMAAAsTAAALEwEAmpwYAAAdMElEQVR4nO3dfZBk11nf8e/TPdM9szO92pfpVYRWawmyxFG5wBYb4cSUUXCJrF2FFIJDpCoITmJEXAgIASpyijKKqlx5KQJUqhQoAY7Nm4UiEmf/EKVQsRKTFBDtohf0guxF2NYuxtuzu5K6Z3e7p6ef/NF9V53x7E7v9L19zz3396na0nTP1Z1Ht7S/OX3uee4xd0dERIqvkncBIiKSDgW6iEgkFOgiIpFQoIuIREKBLiISibm8fvDKyorffPPNef14EZFCOnHixKq7N7f6Xm6BfvPNN3P8+PG8fryISCGZ2Zeu9D1NuYiIREKBLiISCQW6iEgkFOgiIpFQoIuIRGLbQDezT5jZGTN74QrfNzP7D2Z20syeN7Pb0i9TRES2M8kI/ZPA0at8//3A4dGf+4BfnL4sERG5VtuuQ3f3z5nZzVc55G7g13z4HN4/NLM9ZnaDu38lrSKz8jsnTvGls2vbHve3336Adx3aO4OKRER2Lo3GohuB18Zenxq99zWBbmb3MRzFc+jQoRR+9M5d7G3wE//5OQDMrnycO5z48nl+88PvnlFlIiI7M9NOUXd/BHgE4MiRI7nurNFqdwH42b//zXzwWw5e8biP/MYJTp7pzKosEZEdS2OVy2ngprHXB0fvBa3VuQTAynLtqsetLNdpdbqzKElEZCppBPox4B+OVru8G3ijCPPnyQi92ahf9bhmo87rF9bp9jdmUZaIyI5tO+ViZp8G7gBWzOwU8DPAPIC7/xLwBPAB4CRwAfhHWRWbpmsJdICznR5ft2cx87pERHZqklUu927zfQd+OLWKZqTV7lIx2L+0TaAv1y8fr0AXkZCVtlO01emyb6lOtXKVJS68NUJPRvQiIqEqb6C3u9tOt8Bbgb6qG6MiErjyBnqnN1Gg7x+tgtEIXURCV9pAX213L8+PX019rsqeXfNauigiwStloLv7xFMuMFqLrhG6iASulIH+5sU+vY3Btk1FiaYCXUQKoJSBnnSJTjpCbzbULSoi4StloJ+ZsKko0WxohC4i4StloCfhfOAaAv1Cb4O1bj/LskREplLqQG8uL0x0/Hi3qIhIqMoZ6J0utWqF3YuTPT1YzUUiUgSlDPTV9rCpyK62s8UYtf+LSBGUMtBbnS4rE86fw1iga4QuIgErZ6BP2CWa2LurRsU0QheRsJU30BuTNRUBVCvGfjUXiUjgShfoGwPn3Nq1jdBB3aIiEr7SBfrZtS4Dn7ypKKFuUREJXekCfdKt5zZTt6iIhE6BPqFmo85qp8twxz0RkfCUN9An7BJNNJfrrG84b1xcz6IsEZGplS7QVzs9AFauYZULqLlIRMJXukBvtbss1+fYVZus7T+xoue5iEjgyhfoncl3KhqnblERCV35Ar196ZrXoIOmXEQkfCUM9O41z58D7F6YozZXUaCLSLBKGeg7GaGbmbpFRSRopQr0S+sbvHmpv6M5dFC3qIiErVSBnmxQMVWga4QuIoEqWaAP16BPE+jatUhEQlWqQN9pl2hiZbnO2bUe/Y1BmmWJiKSinIE+xQjdHc6t9dIsS0QkFRMFupkdNbNXzOykmT2wxfffZmb/w8yeN7P/aWYH0y91ekmg71++9mWLwOXVMWc0jy4iAdo20M2sCjwMvB+4FbjXzG7ddNjPAr/m7t8EPAT867QLTUOrc4l9SzXmqzv7YKJuUREJ2STJdjtw0t1fdfce8Chw96ZjbgU+O/r6qS2+H4RWu8vKDkfnAAfULSoiAZsk0G8EXht7fWr03rjngL83+vq7gYaZ7d98IjO7z8yOm9nxVqu1k3qnMtxLdGfz56AHdIlI2NK6KfqTwLeb2TPAtwOngY3NB7n7I+5+xN2PNJvNlH705FqdnXWJJhZrVRr1OS1dFJEgTfIM2dPATWOvD47eu8zd/4LRCN3MloHvcffXU6oxFe4+9Qgd1FwkIuGaZIT+NHDYzG4xsxpwD3Bs/AAzWzGz5FwfBT6RbpnTW+ttcGl9MHWgryjQRSRQ2wa6u/eB+4EngZeBx9z9RTN7yMzuGh12B/CKmX0euB74eEb17ti0a9ATzWU9z0VEwjTRtj3u/gTwxKb3Pjb29ePA4+mWlq5pu0QTzUadz31BgS4i4SlNp2hqI/RGnfalPpfWv+aer4hIrkoU6JeAdKZchufTKF1EwlKeQO90qVaMPYvzU51H3aIiEqryBPqoS7RSsanOkwT6qkboIhKYUgX6tNMtoBG6iISrPIE+ZZdoYt9SDTPNoYtIeEoT6KvtXioj9Plqhb27agp0EQlOKQJ9MHBWO+lMucCouUiBLiKBKUWgv35xnf7AU5lygdHzXDSHLiKBKUWgv9VUNF2XaEIP6BKREJUs0FMcobe7uHsq5xMRSUM5Ar0z7BKdZreicc3lOt3+gHa3n8r5RETSUI5Az2CEDmouEpGwlCbQF+YrLNcnerjktpraW1REAlSaQG826phN1/afULeoiISoFIG+2umltmQRtFm0iISpFIGe1nNcEnsW55mrmAJdRIJSjkBPsUsUoFIxVtQtKiKBiT7Q1zcGnFvrTb313GbqFhWR0EQf6Gc7PSC9JYsJdYuKSGiiD/QkdNNqKko0l+usaoQuIgGJP9A76ewlulmzUWe102MwUPu/iIQh/kBPuUs00WzU2Rg45y/0Uj2viMhOlSbQV1Jchz5+Pt0YFZFQRB/oq50euxfmWJivpnpetf+LSGiiD/S0m4oSCnQRCY0CfYcU6CISmvgDvdNNbaeicUu1KovzVQW6iAQj/kBvd1N9MFfCzNQtKiJBiTrQL/T6dLp9VhrpNhUlhmvRFegiEoaJAt3MjprZK2Z20swe2OL7h8zsKTN7xsyeN7MPpF/qtVttj9r+MxihJ+fVlIuIhGLbQDezKvAw8H7gVuBeM7t102E/DTzm7u8C7gH+Y9qF7kRWXaKJlUZNgS4iwZhkhH47cNLdX3X3HvAocPemYxzYPfr6OuAv0itx57LqEk00lxc4f2GdXn+QyflFRK7FJIF+I/Da2OtTo/fGPQh8n5mdAp4AfmSrE5nZfWZ23MyOt1qtHZR7bVoZPWkxkZz37JpG6SKSv7Ruit4LfNLdDwIfAH7dzL7m3O7+iLsfcfcjzWYzpR99Za12l4rB/qVsA13TLiISgkkC/TRw09jrg6P3xv0T4DEAd/8DYAFYSaPAabTaXfYt1alW0tkcejMFuoiEZJJAfxo4bGa3mFmN4U3PY5uO+TLwPgAz++sMAz37OZVtZNUlmlCgi0hItg10d+8D9wNPAi8zXM3yopk9ZGZ3jQ77CeAHzew54NPAh9w99weFp72X6GbJphlaiy4iIZib5CB3f4Lhzc7x9z429vVLwHvSLW16q+0u39Bcyuz89bkq1y3Oa4QuIkGItlPU3TOfcgFtFi0i4Yg20N+82Ke3McisSzSxsqzmIhEJQ7SBnnWXaKLZWFCgi0gQ4g30drZNRQk9z0VEQhFvoI/mtQ/MYA59rbfBWref6c8REdlOvIGePMdlOf3NLcYlnwC0dFFE8hZ1oNeqFXYvTrQyc8cU6CISiqgDvdmoY5ZN238iWUWjeXQRyVu8gd7pspLx/Dmo/V9EwhFvoLe7NJez2Xpu3L6lGhVToItI/uIO9BmM0KsVY9+SukVFJH9RBvrGwDm31s28SzTRbGgtuojkL8pAP7fWY+DZNxUlFOgiEoJs1/TlJOu9RDdrLtc5/sVzfOQ3Tkx9rvlqhZ/6O3+Nm/btSqGy6XW6fR489qIapyQ1f+uvrvD9735b3mVEKc5AH81nr8xoyuXOWw/wwuk3+LNWZ6rzDBxOnulw26E9fOg9t6RU3XSe+fJ5Hj9xikP7drEwH+UHOpmhr77Z5dnXXlegZyTOQG8nbf/Zdokmjr7jBo6+44apzzMYOId/+ndZHW1uHYLkWn7qH9/OLSvZPVteyuHf/O6f8qv/+1XcPfMekTKKcsiVhNBKI/tli2mqVIz9S2E9jnfW01cSt2ajzvqG88bF9bxLiVK0gb5cn2NXrXgfQELbMKPV7rI4X2WpVs27FImAGvGyFWegd7qX9/ssmtBWzCT7surjsaRBj8rIVpyB3r5U2CmC0J6vPqsGLSmHyyP0gD6FxiTSQC9uCDUbdVY7XQYDz7sUIHmEQjGvpYRHUy7ZijLQVzu9woZQs1GnPwjnptFqp7i/HCU8uxfmqM1VNELPSHSB3u1v8MbF9cKGUEgfSXv9AecvFPdaSnjMLLhpxZhEF+jJGu6ihlBIN43OrmnJoqQvtBv/MYku0Iu+bjqkOca3tvEr5rWUMCnQsxNvoGe8l2hWVgIM9FlsFCLlsbJc15aNGYk30AsaQo36HPVAbhoV/VpKmJqNOmfXevQ3BnmXEp1oA31/QRuLzCyYj6SXR+gFvZYSpmajjvvwMdeSrvgCvXOJvbvmma8W9z8tmEDvdLlucZ76nNr+JT3JPZkzAfw/Hpvipt4VFLmpKBHKsq4YrqWEJ6SlubGJLtBXO73Ch1DSLZq31Y66RCV9B0Z/P1cDGLTEZqJAN7OjZvaKmZ00swe2+P7Pm9mzoz+fN7PXU690QjG0qjcbdc5d6LGe800jjdAlC8nGMxqhp2/b58uaWRV4GLgTOAU8bWbH3P2l5Bh3//Gx438EeFcGtW7L3aMIofGbRtfvzm/5ZQzXUsKzWKvSqM8FMa0Ym0lG6LcDJ939VXfvAY8Cd1/l+HuBT6dR3LVa621wcX2j8CEUQrfoWrfPWq/411LCFMqN/9hMEug3Aq+NvT41eu9rmNnbgFuAz17h+/eZ2XEzO95qta611m3Fsm46hOai1RnvyyrlshLIjf/YpH1T9B7gcXff2Oqb7v6Iux9x9yPNZjPlH138LtFECCP0WH45SphC25krFpME+mngprHXB0fvbeUecppugeLuJbpZCMu69BwXyZKmXLIxSaA/DRw2s1vMrMYwtI9tPsjM3g7sBf4g3RIn12pfAoofQgvzVRoL+d40Sn6ZaIQuWWg26rQv9bm0vuWHedmhbQPd3fvA/cCTwMvAY+7+opk9ZGZ3jR16D/Cou+e21U6r06VaMfbuKvYIHfIfwbTaXSoG+5aKfy0lPCFMK8Zo22WLAO7+BPDEpvc+tun1g+mVtTOr7R4ryzUqleJvaNxczneOcbXTZf9ynWoE11LCk3zyW+10uWnfrpyriUdUnaKtiLZLazbquXbSxdCgJeEK6bn/MYkr0CMKoRCmXGL55SjhCeHGf4ziC/RIQqjZqNPu9rnYy+emUUzXUsKzb6mGmUboaYsm0AcDj2qH+qShJ4+HdLk7rU5XTUWSmflqhb27agr0lEUT6K9fXKc/8KimXCCfZ0a/cXGd9Q2P5pejhCmUx0THJJpAj23/yzyXdalLVGZB3aLpiy7QYxmhH8jxplFs11LClPeN/xjFE+idUZdoJKPKPG8aqUtUZiEJ9Bx7EaMTTaCvtocbzsYSQnPVCvuXarncFNWUi8xCc7lOtz+g0+3nXUo0ogn0VqfLwnyF5fpEza+FkNcjRludLrW5CrsX4rmWEh41F6UvnkAfrZs2i6dVPa85xqRBK6ZrKeFRoKcvrkCP7CZeroGu6RbJmLpF0xdXoEcWQskDumZ906jVVlORZG9FT1xMXTyBHlGXaKLZqNPrD3jz0mxvGsXUcSvh2rM4z1zFFOgpiiLQ1zcGnFvrRTeqzGOOsb8x4OxaT4EumatUTHuLpiyKQD/biWvJYiKPbtFzaz3c47uWEiZ1i6YrikCPtbMxj5tGZyK9lhImdYumK4pAX420szGPKRd1icos6QFd6Yoi0GPtbLxucZ75qs20WzTZJelAZNdSwtRs1Dm71mMwUPt/GuII9FHgxXZT1MxmPoKJ9VpKmJqNOhsD5/yFXt6lRCGOQG932b0wx8J8Ne9SUjfrOcZWu0ujPsdiLb5rKeFRc1G6ogn02KZbErNe1tVqd6N5pryET81F6VKgB27Wy7pifISChEvPc0lXHIEe8f6XzUads50uGzO6aRRjx62ES4GerjgCPfIR+sCHDT+zEPO1lPAs1aoszlcV6CkpfKBf7G3Q6fajDaFZdoteWt+gfSneaynhMTN1i6ao8IF+uako4ikXmM0qgFg7biVs6hZNT+ED/UykTUWJ5L9rdQb/w8facSthay7Xc9lqMUaFD/RYu0QTl5d1zXKEHum1lDBphJ6e4gd65KPKpfocS7XZ3DSK/VpKmJqNOucvrNPrD/IupfAmCnQzO2pmr5jZSTN74ArHfK+ZvWRmL5rZb6Vb5pW12l0qBvuX4g2hlRmNYJKfsW+plvnPEkkkn0LPrmmUPq1tt3U3syrwMHAncAp42syOuftLY8ccBj4KvMfdz5vZgawK3qzV7rJvqU61Eu+GxrN6nsvwWtaYrxb+g5sUyPha9BuuW8y5mmKb5G/u7cBJd3/V3XvAo8Ddm475QeBhdz8P4O5n0i3zyob7X8Y9opzVsi51iUoe1FyUnkkC/UbgtbHXp0bvjftG4BvN7P+Y2R+a2dGtTmRm95nZcTM73mq1dlbxJmXobJzVTaMyXEsJjwI9PWl9tp4DDgN3APcCv2xmezYf5O6PuPsRdz/SbDZT+cGrJehsbC7XeePiOt3+RqY/R12ikofkE7YCfXqTBPpp4Kax1wdH7407BRxz93V3/3Pg8wwDPlPuXooQurwWvZNd+39ZrqWEpz5X5brFeXWLpmCSQH8aOGxmt5hZDbgHOLbpmM8wHJ1jZisMp2BeTa/Mrb15qU9vYxD9vO8smos63T7dfvzXUsLUbKi5KA3bBrq794H7gSeBl4HH3P1FM3vIzO4aHfYkcNbMXgKeAn7K3c9mVXSiLI0ws5hjLMu1lDBpb9F0bLtsEcDdnwCe2PTex8a+duCfj/7MTFlCaBbPcynLtZQwNRt1nj/1et5lFF6hFxwnARf7hsZJ01SmI3TtJSo5mvXOXLEqdqBffjrgQs6VZKs2V2HPrnlNuUi0mo06a70N1rr9vEsptMIHeq1aYffiRDNHhZb1HGOr3WWuYuxZnM/sZ4hcyVsruTRKn0bhA31luYZZvG3/iay7RYfXsk4l4kcoSLjUXJSOYgd6iTobs+4WLdO1lPDMcmeumBU70EvUCDOLKZeyXEsJzyx35opZoQN9tUSjymajzsX17G4arXb0YC7Jz76lGhWbzc5cMStsoG8MnLMlCqEs5xgHA2e10yvNL0cJT7Vi7F/WZtHTKmygn1vrMfDyLLPL8iPp+Qs9NgZemmspYVK36PQKG+hlWzed5QhdW89JCLS36PSKG+glC6GVDFcBJOdUl6jkSd2i0ytuoJcshPbuqlGtWKaBXpZfjhKmpNdi+Ggo2QkFekFUK8b+pZoCXaLVbNRZ33DeuLiedymFVehAX6pVWarH3/afyKpbtNXusjhfZalWTf3cIpNSt+j0ihvoJVqDnsjqplFyLcvwCAUJl7pFp1fYQC/DXqKbNZez2dWlTA1aEi51i06vsIFe1hH6aqfLYJDuTaNWuzwNWhIuTblMr7iBXsIQyuqmkZ7jIiHYvTBHba6iEfoUChno3f4Gb1xcL10IZfGRtNcfcP5C+a6lhMfM1C06pUIG+mqnB5RvmV0WzUVn18q1/FPCtqJu0akUMtDLtgY9kcUco9agS0g0Qp9OoQO9bCGkQJfYJTf+ZWcU6AXSqM9RT/mmUVmvpYSp2ahzdq1Hf2OQdymFVOhA379UrhAys9Sbi96avqqldk6RnWo26rgPH48t166Qgb7a6bJ31zy1uUKWP5W0P5KudrpctzhPfU5t/5K/y92imnbZkUImYpnXTad906iMDVoSLjUXTaeYgV7iEMpiyqVsDVoSrgMK9KkUM9BLHELNRp1zF3qsp3TTqMyfdiQ8K5pymUrhAt3dSx1CK8vp3jRqtbulW88v4VqsVVmuz2mEvkOFC/S13gYX1zdKG0JpzjGudfus9TZK+8tRwqS9RXeucIFe9nXTaQb6asn2ZZViULfozk0U6GZ21MxeMbOTZvbAFt//kJm1zOzZ0Z8Pp1/qUOkDPcXnuZT9WkqYstqZqwy23b/NzKrAw8CdwCngaTM75u4vbTr0t939/gxq/P+UPYTSfOLi5WtZ0ukrCVOzUedzX1Cg78QkG3LeDpx091cBzOxR4G5gc6DPxOVpgpKG0MJ8lcbCHL/y+6/ymWdOT3Wu5LnqKw11iUo4mo067Ut97vy5/5V3KZn50fcd5ru++etSP+8kgX4j8NrY61PAt25x3PeY2XuBzwM/7u6vbT7AzO4D7gM4dOjQtVcL3HDdAt956/Xs3VXeEPqx9x3mj798PpVzHdy7q7S/HCVMR9/xV3jlL9v0B/E+z+W6xflMzmvuV9/OzMw+CBx19w+PXn8/8K3j0ytmth/ouHvXzH4I+Afu/h1XO++RI0f8+PHjU/8HiIiUiZmdcPcjW31vkpuip4Gbxl4fHL13mbufdfdk0utXgG/ZSaEiIrJzkwT608BhM7vFzGrAPcCx8QPM7Iaxl3cBL6dXooiITGLbOXR375vZ/cCTQBX4hLu/aGYPAcfd/Rjwo2Z2F9AHzgEfyrBmERHZwrZz6FnRHLqIyLWbdg5dREQKQIEuIhIJBbqISCQU6CIikcjtpqiZtYAvbfGtFWB1xuWkQXXPVlHrhuLWrrpn60p1v83dm1v9C7kF+pWY2fEr3cENmeqeraLWDcWtXXXP1k7q1pSLiEgkFOgiIpEIMdAfybuAHVLds1XUuqG4tavu2brmuoObQxcRkZ0JcYQuIiI7oEAXEYlEUIG+3WbUoTKzL5rZn4w2yA72iWNm9gkzO2NmL4y9t8/Mfs/MvjD65948a9zKFep+0MxOj21M/oE8a9yKmd1kZk+Z2Utm9qKZ/djo/aCv+VXqDvqam9mCmf1fM3tuVPe/Gr1/i5n90ShXfnv0GPBgXKXuT5rZn49d73duezJ3D+IPw0fz/hnw9UANeA64Ne+6Jqz9i8BK3nVMUOd7gduAF8be+3fAA6OvHwD+bd51Tlj3g8BP5l3bNnXfANw2+rrBcHvGW0O/5lepO+hrDhiwPPp6Hvgj4N3AY8A9o/d/CfhI3rVOWPcngQ9ey7lCGqFf3oza3XtAshm1pMTdP8fwefXj7gY+Nfr6U8DfnWVNk7hC3cFz96+4+x+Pvm4z3PjlRgK/5lepO2g+1Bm9nB/9ceA7gMdH74d4va9U9zULKdC32ow6+P+JRhz472Z2YrQRdpFc7+5fGX39l8D1eRZzje43s+dHUzJBTVtsZmY3A+9iOPoqzDXfVDcEfs3NrGpmzwJngN9j+Kn/dXfvjw4JMlc21+3uyfX++Oh6/7yZbbube0iBXmTf5u63Ae8HftjM3pt3QTvhw898RVnH+ovANwDvBL4C/Ptcq7kKM1sGfgf4Z+7+5vj3Qr7mW9Qd/DV39w13fyfDvY9vB96eb0WT2Vy3mb0D+CjD+v8GsA/4F9udJ6RA33Yz6lC5++nRP88A/5Xh/0hF8dVkT9jRP8/kXM9E3P2ro78EA+CXCfSam9k8w1D8TXf/L6O3g7/mW9VdlGsO4O6vA08BfxPYY2bJdptB58pY3UdHU1/u7l3gPzHB9Q4p0LfdjDpEZrZkZo3ka+A7gReu/m8F5RjwA6OvfwD4bznWMrFNG5N/NwFeczMz4FeBl93958a+FfQ1v1LdoV9zM2ua2Z7R14vAnQzn/58CPjg6LMTrvVXdfzr2S98Yzvtve72D6hQdLYP6Bd7ajPrj+Va0PTP7eoajchhuuv1bodZtZp8G7mD4WM6vAj8DfIbhKoBDDB9n/L3uHtQNyCvUfQfDj/7OcJXRD43NSwfBzL4N+H3gT4DB6O1/yXA+OthrfpW67yXga25m38TwpmeV4WD1MXd/aPR39FGG0xbPAN83GvUG4Sp1fxZoMlwF8yzwT8dunm59rpACXUREdi6kKRcREZmCAl1EJBIKdBGRSCjQRUQioUAXEYmEAl1EJBIKdBGRSPw/tCjFYIcNQ+oAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "plt.plot(k_value,accuracy)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
